// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwyorswmjdmwddmrovuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eW9yc3dtamRtd2RkbXJvdnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODM4ODYsImV4cCI6MjA1Nzc1OTg4Nn0.psGKdZlNX8kPSp95G3A6otI02UH_jjSEXdfMoV1KXLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);